# Generated by Django 5.0.6 on 2024-05-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0013_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.CharField(choices=[('$', 'US Dollar $'), ('£ ', 'Pound Sterling £'), ('€', 'Euro €')], default='US Dollar $', max_length=24),
        ),
    ]
