# Generated by Django 5.0.6 on 2024-05-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0014_deposit_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.CharField(choices=[('US Dollar $', '$'), ('Pound Sterling £ ', '£'), ('Euro €', '€')], default='$', max_length=24),
        ),
    ]
