# Generated by Django 5.0.6 on 2024-05-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0015_alter_deposit_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('£ ', '£'), ('€', '€')], default='$', max_length=24),
        ),
    ]
