# Generated by Django 5.0.6 on 2024-05-21 00:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0016_alter_deposit_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction1',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=200, null=True)),
                ('transaction_id', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=200, null=True)),
                ('type', models.CharField(choices=[('bitcoin', 'bitcoin'), ('transfer', 'transfer'), ('cashapp', 'cashapp'), ('skril', 'skril'), ('Western Union', 'Western Union'), ('paypal', 'paypal')], max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
