# Generated by Django 5.0.6 on 2024-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0017_remove_transaction1_date_transaction1_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
