# Generated by Django 5.0.6 on 2024-05-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0018_alter_withdraw_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction1',
            name='created_at',
        ),
        migrations.AddField(
            model_name='transaction1',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
