# Generated by Django 5.0.6 on 2024-05-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0019_remove_transaction1_created_at_transaction1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('You need to have a Withdrawal Pin in order to facilitate your withdrawal request. Please contact an agent for help on how to get one.', 'You need to have a Withdrawal Pin in order to facilitate your withdrawal request. Please contact an agent for help on how to get one.'), ('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info'), ('KYC has not been uploaded kindly contact customercare for more information', 'KYC has not been uploaded kindly contact customercare for more information')], default='You need to have a Withdrawal Pin in order to facilitate your withdrawal request. Please contact an agent for help on how to get one.', max_length=200, null=True),
        ),
    ]
