# Generated by Django 5.0.6 on 2024-05-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0020_alter_alert_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='kyc',
        ),
        migrations.AddField(
            model_name='deposit',
            name='alert',
            field=models.CharField(choices=[('sweetAlert', 'sweetAlert'), ('stop', 'stop')], default='sweetAlert', max_length=24),
        ),
    ]
