# Generated by Django 5.0.6 on 2024-05-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0023_alter_deposit_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='alert',
            field=models.CharField(choices=[('sweetAlert', 'sweetAlert'), ('stop1', 'stop1')], default='sweetAlert', max_length=24),
        ),
    ]
